parameters:
    sqsRegion: ""

services:
    sqsClient:
        class: Aws\Sqs\SqsClient
        arguments:
            -
                version: "2012-11-05"
                region: "%sqsRegion%"

    messageFactory:
        class: Silktide\QueueBall\Sqs\MessageFactory

    abstractSqsQueue:
        abstract: true
        class: Silktide\QueueBall\Sqs\Queue
        arguments:
            client: "@sqsClient"
            messageFactory: "@messageFactory"
            queueId: null

    sqsQueue:
        extends: "abstractSqsQueue"

    # set the sqs queue to be default
    silktide_queueball.defaultQueue:
        aliasOf: "@sqsQueue"

