parameters:
    sqsRegion: ""

    # SQS has a max filesize limit of 256kb, if it's bigger than that, we want to store the file in S3 and fetch it
    # from there instead
    sizeThreshold: 200000
    storageBucket: cache.silktide.com
    storagePrefix: "sqs/"

services:
    sqsClient:
        class: Aws\Sqs\SqsClient
        arguments:
            -
                version: "2012-11-05"
                region: "%sqsRegion%"

    messageFactory:
        class: Silktide\QueueBall\Sqs\MessageFactory

    abstractSqsQueue:
        abstract: true
        class: Silktide\QueueBall\Sqs\Queue
        arguments:
            - "@sqsClient"
            - "@messageFactory"
            - "@middlewareGroup"

    middlewareGroup:
        class: Silktide\Queueball\Sqs\MiddlewareGroup
        arguments:
          -
            - "@jsonMiddleware"
            - "@largeFileMiddleware"

    jsonMiddleware:
        class: Silktide\Queueball\Sqs\JsonMiddleware

    largeFileMiddleware:
        class: Silktide\Queueball\Sqs\LargeFileMiddleware
        arguments:
          - "@s3Client"
          - "%storageBucket%"
          - "%storagePrefix%"
          - "%sizeThreshold%"

    sqsQueue:
        extends: "abstractSqsQueue"

    # set the sqs queue to be default
    silktide_queueball.defaultQueue:
        aliasOf: "@sqsQueue"

